//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACOVIDWEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos
    {
        public int id_datos { get; set; }
        public string pais { get; set; }
        public string region { get; set; }
        public string ano { get; set; }
        public string area { get; set; }
        public string sexo { get; set; }
        public string grupo_edad { get; set; }
        public string clima_educativo { get; set; }
        public string nivel_ingresos { get; set; }
        public string indicador { get; set; }
        public string valor_indicador { get; set; }
        public string factor { get; set; }
        public string muestra { get; set; }
    
        public virtual labels_area labels_area { get; set; }
        public virtual labels_indicador labels_indicador { get; set; }
        public virtual labels_pais labels_pais { get; set; }
        public virtual labels_sexo labels_sexo { get; set; }
    }
}
